<?php

class MarkupCrossfade extends WireData implements Module
{
    public static function getModuleInfo() {
        return array(
            'title'    => __('Markup Cross-Fade', __FILE__),
            'summary'  => __('Generates CSS3 Key-frame-animated cross fades.', __FILE__),
            'version'  => 1,
            'autoload' => false,
            'author'   => 'Stephen Dickinson, QBox.co',
        );
    }


    public function getParams($pages = null)
    {
        return array(
            'pages'             => $pages,             // WireArray of pages defining the slides of the slideshow.
            'duration_field'    => 'duration',         // Field of the slide page that provides the duration (in seconds)
            'overlay_field'     => 'body',             // Field of the slide page that provides the overlay text
            'image_field'       => 'image',            // Field of the slide page that provides the image (url)
            'title_xform_field' => '',                 // Field of the slide page that provides the title transformations
            'image_xform_field' => '',                 // Field of the slide page that provides the image transformations
            'title_xforms'      => '',                 // Default title transformations - one per line (\n separator please) - leave blank for none.
            'image_xforms'      => '',                 // Default image transformations - one per line (\n separator please) - leave blank for none.
            'html_class'        => 'markup-crossfade', // What class to apply to the owning list
            'z_index'           => '-10',              // z-index of slideshow container and it's spans
            'li_id'             => 'slide_',           // What id to use for each slide. The slide # will be appended to this
            'browsers'          => array(              // Array of browsers extensions to generate CSS for
                '',
                '-webkit-',
                '-moz-',
                '-o-',
                '-ms-'
            ),
            'skip_css'          => false,              // true => use your own CSS file.
            'mask_image'        => '',                 // location of mask image. Leave blank if none.
        );
    }


    protected static function calcTimings(array $params)
    {
        $params = array_merge(self::getParams(), $params);
        extract($params, EXTR_PREFIX_ALL, 'param');

        $num_panels = $param_pages->getTotal();
        if ($num_panels == 0) {
            throw new \WireException(__('You must define which pages are to be used as slides for the crossfade.', __FILE__));
        }

        $timings = array(
            'total' => 0,
            'panels' => array(
            ),
            'html_class' => $param_html_class,
            'li_id' => $param_li_id,
            'browsers' => $param_browsers,
            'z_index' => $param_z_index,
            'skip_css' => $param_skip_css,
            'mask_image' => $param_mask_image,
        );

        foreach ($param_pages as $z => $p) {
            $images = $p->$param_image_field;
            if (null === $images) {
                $image = '';
            } else if ($images instanceof WireArray) {
                $image = $images->first->url;
            } else {
                $image = $images->url;
            }


            $panel_duration = $p->$param_duration_field;
            $timings['panels'][$z+1]['delay']      = $timings['total'];
            $timings['panels'][$z+1]['url']        = $image;
            $timings['panels'][$z+1]['duration']   = $panel_duration;
            if (null !== $p->$param_title_xform_field) {
                $timings['panels'][$z+1]['ttl_xforms'] = $p->$param_title_xform_field;
            } else {
                $timings['panels'][$z+1]['ttl_xforms'] = $param_title_xforms;
            }
            if (null !== $p->$param_image_xform_field) {
                $timings['panels'][$z+1]['img_xforms'] = $p->$param_image_xform_field;
            } else {
                $timings['panels'][$z+1]['img_xforms'] = $param_image_xforms;
            }
            $timings['total'] += (int) $panel_duration;
        }

        $total = $timings['total'];
        foreach ($timings['panels'] as $i => &$info) {
            $finish_pc = (int) bcdiv(bcmul("100", $info['duration'], 2), "$total", 2);
            $half_pc   = (int) bcdiv($finish_pc, "2", 2);
            $done_pc   = $finish_pc + $half_pc;
            if ($done_pc > 100) {
                $done_pc = 100;
            }

            $keyframes_images = array(
                "0%" => 0,
                "$half_pc%" => 1,
                "$finish_pc%" => 1,
                "$done_pc%" => 0,
                "100%" => 0,
            );

            $half_pc += 0;
            $done_pc -= 0;

            $keyframes_titles = array(
                "0%" => 0,
                "$half_pc%" => 1,
                "$finish_pc%" => 1,
                "$done_pc%" => 0,
                "100%" => 0,
            );

            $info['keyframes-images'] = $keyframes_images;
            $info['keyframes-titles'] = $keyframes_titles;
        }

        return $timings;
    }


    public static function generateCss(array $params)
    {
        $times = self::calcTimings($params);
        $total = $times['total'];
        $html_class = $times['html_class'];
        $li_id      = $times['li_id'];
        $browsers   = $times['browsers'];
        $skip_css   = $times['skip_css'];
        $z_index    = $times['z_index'];
        $mask_image = $times['mask_image'];

        $static_css = '';
        if (!$skip_css) {
            $static_css_file = dirname(__FILE__).'/MarkupCrossfade.css';
            $static_css = file_get_contents($static_css_file);
            if (false === $static_css) {
                throw new \WireException(__("Could not find file '$static_css_file'", __FILE__));
            }
            $static_css = str_replace('{{html_class}}', $html_class, $static_css);
            $static_css = str_replace('{{z_index}}', $z_index, $static_css);

            $replace = '';
            if (is_string($mask_image) && !empty($mask_image)) {
                $replace = ".$html_class:after {
    content: '';
    background: transparent url($mask_image) repeat top left;
}";
            }
            $static_css = str_replace('{{mask_image}}', $replace, $static_css);
        }
        $css = '';

        $image_frame_cache = array();
        $title_frame_cache = array();

        foreach ($times['panels'] as $i => $info) {
            $delay      = $info['delay'];

            $ttl_xforms = explode("\n", $info['ttl_xforms']);
            $img_xforms = explode("\n", $info['img_xforms']);

            $img_kf = '';
            $j = 0;
            foreach ($info['keyframes-images'] as $pc => $opacity) {

                // Add opacity...
                $x = array("opacity:$opacity");

                // Add easing...
                if (0 === $j) {
                    $x[] = '{browser}animation-timing-function:ease-in';
                } else if (1 === $j) {
                    $x[] = '{browser}animation-timing-function:ease-out';
                }

                // Add image transformations...
                if (isset($img_xforms[$j]) && !empty(trim($img_xforms[$j]))) {
                    $x[] = "transform:{$img_xforms[$j]}";
                }

                // Merge this keyframe...
                $x = '{'.implode("; ", $x).';}';
                $img_kf .= "\t$pc $x\n";
                $j++;
            }

            $ttl_kf = '';
            $j = 0;
            foreach ($info['keyframes-titles'] as $pc => $opacity) {

                // Add opacity...
                $x = array("opacity:$opacity");

                // Add title transformations...
                if (isset($ttl_xforms[$j]) && !empty(trim($ttl_xforms[$j]))) {
                    $x[] = "transform:{$ttl_xforms[$j]}";
                }

                // Merge this keyframe...
                $x = '{'.implode("; ", $x).';}';
                $ttl_kf .= "\t$pc $x\n";
                $j++;
            }

            $image_kf_key = md5($img_kf);
            $title_kf_key = md5($ttl_kf);
            $image_kf = '';
            $title_kf = '';

            foreach ($browsers as $browser) {
                $tmp_image_kf = str_replace('{browser}', $browser, $img_kf);
                $tmp_title_kf = str_replace('{browser}', $browser, $ttl_kf);

                $image_kf .= "@{$browser}keyframes img_ani_{$i} {\n$tmp_image_kf}\n";
                $title_kf .= "@{$browser}keyframes ttl_ani_{$i} {\n$tmp_title_kf}\n";
            }

            if (!array_key_exists($image_kf_key, $image_frame_cache)) {
                $image_frame_cache[$image_kf_key] = array($i, $image_kf);
                $css .= $image_kf;
            }

            if (!array_key_exists($title_kf_key, $title_frame_cache)) {
                $title_frame_cache[$title_kf_key] = array($i, $title_kf);
                $css .= $title_kf;
            }

            $image_index = $image_frame_cache[$image_kf_key][0];
            $title_index = $title_frame_cache[$title_kf_key][0];
            $css_img = array();
            $css_ttl = array();
            $css_del = array();

            foreach ($browsers as $browser) {
                $css_img[] = "\t{$browser}animation: img_ani_{$image_index} {$total}s linear infinite 0s;";
                $css_ttl[] = "\t{$browser}animation: ttl_ani_{$image_index} {$total}s linear infinite 0s;";
                $css_del[] = "\t{$browser}animation-delay: {$delay}s;";
            }
            $css_img = implode("\n", $css_img);
            $css_ttl = implode("\n", $css_ttl);
            $css_del = implode("\n", $css_del);

            $css .=<<<CSS
.{$html_class} li#{$li_id}{$i} span {
\tbackground-image: url('{$info['url']}');
$css_img
$css_del
}
.{$html_class} li#{$li_id}{$i} div {
$css_ttl
$css_del
}

CSS;
        }

        return "$static_css\n$css";
    }


    function generateHtml(array $params)
    {
        $params = array_merge(self::getParams(), $params);
        extract($params, EXTR_PREFIX_ALL, 'param');

        $num_panels = $param_pages->getTotal();
        if ($num_panels == 0) {
            throw new \WireException(__('You must define which pages are to be used as slides for the crossfade.', __FILE__));
        }

        $o[] = '<ul class="'.$param_html_class.'">';
        foreach ($param_pages as $z => $p) {
            $i = $z + 1;
            $o[] = "<li id=\"$param_li_id$i\">";
            $o[] = "\t<span>Panel $i</span>";
            $o[] = "\t<div>";
            if ($p->$param_overlay_field) {
                $o[] = "\t\t<h3>{$p->$param_overlay_field}</h3>";
            }
            $o[] = "\t</div>";
            $o[] = '</li>';
        }
        $o[] = '</ul>';
        $o = implode("\n", $o);
        return $o;
    }
}

//eof
